# Make sure we're using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install GNU utilities (without prefixes)
install coreutils --default-names
install findutils --default-names

# Install wget with IRI support
install wget --enable-iri

# Install more recent versions of some OS X tools
tap homebrew/dupes
install homebrew/dupes/grep
install homebrew/dupes/rsync


# Install everything else
install git
install node
install rename
install ack
install tree
install hub
install z
install git-extras

# Remove outdated versions from the cellar
cleanup

# Check if installation is successfully
doctor