# Install command-line tools using Homebrew
# Usage: `brew bundle Brewfile`

# Make sure we're using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install GNU utilities (without prefixes)
# Those that come with OS X are outdated
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
install coreutils --default-names
install findutils --default-names

# Install wget with IRI support
install wget --enable-iri

# Install more recent versions of some OS X tools
tap homebrew/dupes
# install homebrew/dupes/rsync

# Install everything else
install ack
install fasd
install git
install git-extras
install node
install rename
install tree
# install hub (try this)

# Remove outdated versions from the cellar
cleanup

# Check if installation is successfully
doctor