---
- hosts: localhost
  tasks:
    - name: Find all available modules directories except those that starts with an underscore
      find:
        paths: "{{ playbook_dir }}/modules"
        file_type: directory
        patterns: "^[^_]*$"
        use_regex: yes
      register: modules

    - name: Find all available command directories
      find:
        paths: "{{ modules.files | map(attribute='path') | list }}"
        patterns: 'commands'
        file_type: directory
      register: command_dirs

    - name: "Store given module {{ command }} command"
      set_fact:
        target_command_dirs: "{{ command_dirs.files | map(attribute='path') | select('match', '.*/' + module + '/commands') | list }}"
      when: module is defined

    - name: "Store all modules {{ command }} commands"
      set_fact:
        target_command_dirs: "{{ command_dirs.files | map(attribute='path') | list }}"
      when: module is undefined

    - name: "Find all available {{ command }} tasks"
      find:
        paths: "{{ target_command_dirs }}"
        patterns: "{{ command }}.yml"
      register: command_tasks

    - name: Include tasks files from all available modules
      include_tasks: "{{ playbook_tasks }}"
      loop: "{{ command_tasks.files | map(attribute='path') | list }}"
      loop_control:
        loop_var: playbook_tasks
