#!/bin/sh

pushd $(dirname $0) > /dev/null

CURRENT_DIR=`pwd`

popd > /dev/null


function is_osx {
  [[ "$OSTYPE" =~ ^darwin ]] || return 1
}

function is_ubuntu {
  [[ "$(cat /etc/issue 2> /dev/null)" =~ Ubuntu ]] || return 1
}

function command_line_tools_are_installed {
  [[ ! "$(type -P brew)" ]] || return 1
}

function install_command_line_tools {
  if [[ command_line_tools_are_installed ]]; then
    echo "XCode Command Line Tools are already installed"
  else
    echo "Installing XCode Command Line Tools"
  fi
}

function homebrew_is_installed {
  [[ ! "$(type -P brew)" ]] && return 1
}

function install_homebrew {
  if [[ homebrew_is_installed ]]; then
    echo "Homebrew is already installed"
  else
    echo "\033[0;32mInstalling Homebrew...\033[0m"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    if [[ homebrew_is_not_installed ]]; then
      echo "\033[0;31mError:\033[0m Homebrew failed to install"
      return 1
    fi
  fi

  brew doctor ||
  echo '\033[0;31mError:\033[0m Fix the problems reported by brew doctor and run the install command again' &&
  return 1
}

function ansible_is_installed {
  [[ ! "$(type -P ansible)" ]] && return 1
}

function install_ansible {
  if [[ ansible_is_installed ]]; then
    echo "Ansible is already installed"
  else
    echo "Installing Ansible..."
    brew install ansible
  fi
}


function main {
  if [[ is_osx ]]; then
    echo "Running Mac OS installation..."

    install_command_line_tools &&
    install_homebrew &&
    install_ansible &&
    ansible-playbook -i "$CURRENT_DIR/inventory" "$CURRENT_DIR/main.yml" --ask-become-pass ||
    exit 1

  elif [[ is_ubuntu ]]; then
    echo "This machine is using a Ubuntu system. None of the tools has been installed"
    exit 1
  else
    echo "This machine is using a system different from Ubuntu or Mac OS. None of the tools has been installed"
    exit 1
  fi
}

main

unset -f \
  is_osx \
  is_ubuntu \
  command_line_tools_are_installed \
  install_command_line_tools \
  homebrew_is_installed \
  install_homebrew \
  ansible_is_installed \
  install_ansible \
  main
