---
packages_to_install:
  - akamud.vscode-theme-onedark
  - bmalehorn.vscode-fish
  - bradlc.vscode-tailwindcss
  - christian-kohler.path-intellisense
  - dbaeumer.vscode-eslint
  - esbenp.prettier-vscode
  - github.copilot
  - mrmlnc.vscode-scss
  - ms-azuretools.vscode-docker
  - redhat.vscode-yaml
  - wmaurer.vscode-jumpy