#!/usr/bin/env bash

if [[ -d "$dotfiles" ]]; then
  echo "Symlinking dotfiles from $dotfiles"
else
  echo "$dotfiles does not exist"
  exit 1
fi

  link (){
    if [ -e $1 ]; then
      if [ -e $2 ]; then
        rm $2
      fi

      ln -s $1 $2
    fi
  }

  link_files () {
  ln -s $1 $2
  success "linked $1 to $2"
}

  # bash
  link ~/cl/etc/bash_profile ~/.bash_profile
  link ~/cl/etc/bashrc ~/.bashrc
  link ~/cl/etc/bashrc_help ~/.bashrc_help
  link ~/cl/etc/bashrc_app_specific ~/.bashrc_app_specific

  # vim
  link ~/cl/etc/vim/vimrc ~/.vimrc
  link ~/cl/etc/vim/gvimrc ~/.gvimrc
  link ~/cl/etc/vim ~/.vim

  # git
  link ~/cl/etc/gitconfig ~/.gitconfig
  link ~/cl/etc/gitignore ~/.gitignore
  link ~/cl/etc/gitattributes ~/.gitattributes

  # misc
  link ~/cl/etc/subversion ~/.subversion
  link ~/cl/etc/autotest ~/.autotest
  link ~/cl/etc/irbrc ~/.irbrc
  link ~/cl/etc/ssh_config ~/.ssh/config

  source ~/.bash_profile

fi


dev="$HOME/Development"
dotfiles="$dev/paulmillr/dotfiles"
bin="/usr/local/bin"

link() {
  from="$1"
  to="$2"
  echo "Linking '$from' to '$to'"
  rm --force "$to"
  ln -s "$from" "$to"
}

for location in home/*; do
  file="${location##*/}"
  file="${file%.*}"
  link "$dotfiles/$location" "$HOME/.$file"
done

for location in bin/*; do
  file="${location##*/}"
  file="${file%.*}"
  link "$dotfiles/$location" "$bin/$file"
done