#!/usr/bin/env bash

# Ensure that we can actually, like, compile anything.
if [[ ! "$(type -P gcc)" && "$OSTYPE" =~ ^darwin ]]; then
  e_error "XCode or the Command Line Tools for XCode must be installed first."
  exit 1
fi

if [[ ! -d "$('xcode-select' -print-path 2>/dev/null)" ]]; then
  sudo xcode-select -switch /usr/bin
fi

# Install dependencies (brew, xcode...)
  xcode-select --install

# Comprobar que la ruta de brew esta por delante de la otra para que brew funcione bien


  which -s brew
  if [[ $? != 0 ]]; then
    echo 'Installing Homebrew...'
      ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
      brew update
  fi
  
  # Install homebrew and some packages
  brew bundle "$brewfile_path"

  # Install apps through homebrew cask
  brew bundle "$caskfile_path"

  # Change default osx settings
  source "$osx_path"
fi